title:  lateral &middot; stories
email: lateral.stories@xiple.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Lateral Stories in Design
baseurl: "/lateralstories" # the subpath of your site, e.g. /blog
domain: "https://stories.lateralco.studio"
url: https://dopamine.github.io/lateralstories # the base hostname & protocol for your site, e.g. http://example.com
imgsrc: "https://pub-e5c465795334447881100228fc123407.r2.dev"
twitter_username: zita.freeburn
github_username:  dopamine

author:
  name: Zita
  url: https://xiple.co.uk
  email: hello@xiple.co.uk

nav_pages:
  - index.md
  - stories.md
  - about.md

rss: "atom.xml"

collections:
  test:
    output: true

# Build settings
# theme: minima

sass:
  sass_dir: assets/_scss

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

exclude:
 - setup.md
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - CNAME
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/